print("1-¿Cuál es la función de la memoria secundaria en una computadora?")
print("a) Ejecutar todos los cálculos y la lógica del programa.")
print("b) Descargar páginas web de Internet.")
print("c) Almacenar información durante mucho tiempo, incluso después de ciclos de apagado y encendido.")
print("d) Recolectar la entrada del usuario.")
print("Respuesta: c")

print("2-¿Qué es un programa?")
print("Respuesta: Un programa es un conjunto de instrucciones que una computadora puede interpretar y ejecutar para realizar tareas específicas.")

print("3-¿Cuál es la diferencia entre un compilador y un intérprete?")
print("Respuesta: Un compilador traduce todo el código fuente a código máquina antes de ejecutarlo, mientras que un intérprete traduce y ejecuta línea por línea.")

print("4-¿Cuál de los siguientes contiene 'código máquina'?")
print("a) El intérprete de Python.")
print("b) El teclado.")
print("c) El código fuente de Python.")
print("d) Un documento de un procesador de texto.")
print("Respuesta: a")

print("5-¿Qué está mal en el siguiente código?:")
print(">>> primt '¡Hola, mundo!'")
print("Respuesta: La instrucción 'primt' está mal escrita, la correcta es 'print'.")

print("6-¿En qué lugar del computador queda almacenada una variable, como en este caso 'x', después de ejecutar la siguiente línea de Python?:")
print("x = 123")
print("a) Unidad central de procesamiento.")
print("b) Memoria Principal.")
print("c) Memoria Secundaria.")
print("d) Dispositivos de Entrada.")
print("e) Dispositivos de Salida.")
print("Respuesta: b")

print("7-¿Qué mostrará en pantalla el siguiente programa?:")
print("x = 43")
print("x = x + 1")
print("print(x)")
print("a) 43.")
print("b) 44.")
print("c) x + 1.")
print("d) Error, porque x = x + 1 no es posible matemáticamente.")
print("Respuesta: b")

print("8-Explica cada uno de los siguientes conceptos usando un ejemplo de una capacidad humana:")
print("Unidad central de procesamiento: Es como el cerebro humano, que toma decisiones y procesa información.")
print("Memoria principal: Es como la memoria a corto plazo, que almacena información temporalmente.")
print("Memoria secundaria: Es como la memoria a largo plazo, que guarda información para un uso futuro.")
print("Dispositivos de entrada: Son como los sentidos humanos, que reciben información del entorno.")
print("Dispositivos de salida: Son como la voz o las acciones, que permiten comunicar información.")

print("9-¿Cómo puedes corregir un 'Error de sintaxis'?")
print("Respuesta: Revisando el código, corrigiendo errores tipográficos y asegurándose de seguir las reglas del lenguaje de programación.")